// <auto-generated />
using System;
using Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(HarryPotterContext))]
    [Migration("20240126164700_Namings")]
    partial class Namings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Author", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("authorId");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("authorName");

                    b.HasKey("AuthorId")
                        .HasName("PK__author__8E2731B93441940C");

                    b.ToTable("author", (string)null);

                    b.HasData(
                        new
                        {
                            AuthorId = new Guid("534d41c8-e176-4a14-af49-656aa13922c0"),
                            AuthorName = "J.K Rowling"
                        },
                        new
                        {
                            AuthorId = new Guid("048c1636-4cfd-4dc8-bd29-8e3326db8c07"),
                            AuthorName = "Alan Rickman"
                        },
                        new
                        {
                            AuthorId = new Guid("4553d538-afa6-419e-b385-058a76177fd1"),
                            AuthorName = "Stephen King"
                        });
                });

            modelBuilder.Entity("Domain.Models.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bookId");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("authorId");

                    b.Property<string>("Genre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("genre");

                    b.Property<int?>("Pages")
                        .HasColumnType("int")
                        .HasColumnName("pages");

                    b.Property<DateTime?>("PubYear")
                        .HasColumnType("datetime")
                        .HasColumnName("pubYear");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("rating");

                    b.Property<int?>("StockBalance")
                        .HasColumnType("int")
                        .HasColumnName("stockBalance");

                    b.Property<string>("Summary")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("BookId")
                        .HasName("PK__book__8BE5A10DE068B40D");

                    b.HasIndex("AuthorId");

                    b.ToTable("book", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = new Guid("5e084454-9e07-4f75-b0f1-13aefdd91180"),
                            AuthorId = new Guid("534d41c8-e176-4a14-af49-656aa13922c0"),
                            Genre = "Action",
                            Pages = 250,
                            PubYear = new DateTime(2024, 1, 26, 16, 47, 0, 59, DateTimeKind.Utc).AddTicks(2867),
                            Rating = 4.5m,
                            StockBalance = 10,
                            Summary = "Action packed book",
                            Title = "Book 1"
                        },
                        new
                        {
                            BookId = new Guid("b195c337-a4cc-49f5-b075-cffe9faeac44"),
                            AuthorId = new Guid("048c1636-4cfd-4dc8-bd29-8e3326db8c07"),
                            Genre = "Comedy",
                            Pages = 300,
                            PubYear = new DateTime(2024, 1, 26, 16, 47, 0, 59, DateTimeKind.Utc).AddTicks(2873),
                            Rating = 3.7m,
                            StockBalance = 20,
                            Summary = "Very funny book",
                            Title = "Book 2"
                        },
                        new
                        {
                            BookId = new Guid("e76e9cf6-c59c-444c-bffb-fa0276c7d9c4"),
                            AuthorId = new Guid("4553d538-afa6-419e-b385-058a76177fd1"),
                            Genre = "Drama",
                            Pages = 180,
                            PubYear = new DateTime(2024, 1, 26, 16, 47, 0, 59, DateTimeKind.Utc).AddTicks(2876),
                            Rating = 4.8m,
                            StockBalance = 10,
                            Summary = "So much drama",
                            Title = "Book 3"
                        });
                });

            modelBuilder.Entity("Domain.Models.PurchaseHistory", b =>
                {
                    b.Property<Guid>("PurchaseHistoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("purchaseHistoryId");

                    b.Property<DateTime?>("TimeOfPurchase")
                        .HasColumnType("datetime")
                        .HasColumnName("timeOfPurchase");

                    b.Property<int?>("TotalPrice")
                        .HasColumnType("int")
                        .HasColumnName("totalPrice");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.HasKey("PurchaseHistoryId")
                        .HasName("PK__purchase__0261226C79359CBF");

                    b.HasIndex("UserId");

                    b.ToTable("purchaseHistory", (string)null);

                    b.HasData(
                        new
                        {
                            PurchaseHistoryId = new Guid("23166c5e-8805-4126-9f3c-716e0b6509cd"),
                            TimeOfPurchase = new DateTime(2024, 1, 26, 16, 47, 0, 59, DateTimeKind.Utc).AddTicks(2927),
                            TotalPrice = 50,
                            UserId = new Guid("30e6d5b1-eee9-4d50-93f7-6e8ee36b1b4a")
                        },
                        new
                        {
                            PurchaseHistoryId = new Guid("0847551c-49a5-4dcd-8bc4-0f1f09b2b824"),
                            TimeOfPurchase = new DateTime(2024, 1, 26, 16, 47, 0, 59, DateTimeKind.Utc).AddTicks(2928),
                            TotalPrice = 30,
                            UserId = new Guid("30e6d5b1-eee9-4d50-93f7-6e8ee36b1b4a")
                        },
                        new
                        {
                            PurchaseHistoryId = new Guid("38ddf893-d431-414f-a633-4bb2f465f3a2"),
                            TimeOfPurchase = new DateTime(2024, 1, 26, 16, 47, 0, 59, DateTimeKind.Utc).AddTicks(2929),
                            TotalPrice = 25,
                            UserId = new Guid("30e6d5b1-eee9-4d50-93f7-6e8ee36b1b4a")
                        });
                });

            modelBuilder.Entity("Domain.Models.Receipt", b =>
                {
                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReceiptId");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bookId");

                    b.Property<DateTime?>("DateDetail")
                        .HasColumnType("datetime")
                        .HasColumnName("dateDetail");

                    b.Property<int?>("PricePerUnit")
                        .HasColumnType("int")
                        .HasColumnName("pricePerUnit");

                    b.Property<Guid?>("PurchaseHistoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("purchaseHistoryId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("ReceiptId")
                        .HasName("PK__purchase__FA43B55BADA17CED");

                    b.HasIndex("BookId");

                    b.HasIndex("PurchaseHistoryId");

                    b.ToTable("Receipt", (string)null);

                    b.HasData(
                        new
                        {
                            ReceiptId = new Guid("27ae00d4-421d-4e9e-a8cd-4dc0c38f566e"),
                            BookId = new Guid("5e084454-9e07-4f75-b0f1-13aefdd91180"),
                            DateDetail = new DateTime(2024, 1, 26, 16, 47, 0, 59, DateTimeKind.Utc).AddTicks(2946),
                            PricePerUnit = 100,
                            PurchaseHistoryId = new Guid("23166c5e-8805-4126-9f3c-716e0b6509cd"),
                            Quantity = 2
                        },
                        new
                        {
                            ReceiptId = new Guid("2f67be43-d96d-4a1e-af3d-0d5c09f36ad8"),
                            BookId = new Guid("b195c337-a4cc-49f5-b075-cffe9faeac44"),
                            DateDetail = new DateTime(2024, 1, 26, 16, 47, 0, 59, DateTimeKind.Utc).AddTicks(2949),
                            PricePerUnit = 150,
                            PurchaseHistoryId = new Guid("0847551c-49a5-4dcd-8bc4-0f1f09b2b824"),
                            Quantity = 1
                        },
                        new
                        {
                            ReceiptId = new Guid("717c735d-b8d1-4db9-82ce-a5d8b0c9288a"),
                            BookId = new Guid("e76e9cf6-c59c-444c-bffb-fa0276c7d9c4"),
                            DateDetail = new DateTime(2024, 1, 26, 16, 47, 0, 59, DateTimeKind.Utc).AddTicks(2950),
                            PricePerUnit = 80,
                            PurchaseHistoryId = new Guid("38ddf893-d431-414f-a633-4bb2f465f3a2"),
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("firstName");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("role");

                    b.Property<string>("SurName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("surName");

                    b.Property<string>("TelephoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telephoneNumber");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userName");

                    b.HasKey("UserId")
                        .HasName("PK__user__CB9A1CFF7FE751DC");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("30e6d5b1-eee9-4d50-93f7-6e8ee36b1b4a"),
                            UserName = "AnvändareTestKöphistorik"
                        });
                });

            modelBuilder.Entity("Domain.Models.Wallet", b =>
                {
                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("walletId");

                    b.Property<int?>("Balance")
                        .HasColumnType("int")
                        .HasColumnName("balance");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WalletId")
                        .HasName("PK__wallet__3785C8706E62B1A8");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("wallet", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Book", b =>
                {
                    b.HasOne("Domain.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("FK__book__authorId__4222D4EF");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Domain.Models.PurchaseHistory", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("PurchaseHistories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__purchaseH__userI__412EB0B6");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Receipt", b =>
                {
                    b.HasOne("Domain.Models.Book", "Book")
                        .WithMany("Receipts")
                        .HasForeignKey("BookId")
                        .HasConstraintName("FK__purchaseD__bookI__440B1D61");

                    b.HasOne("Domain.Models.PurchaseHistory", "PurchaseHistories")
                        .WithMany("Receipts")
                        .HasForeignKey("PurchaseHistoryId")
                        .HasConstraintName("FK__purchaseD__purch__4316F928");

                    b.Navigation("Book");

                    b.Navigation("PurchaseHistories");
                });

            modelBuilder.Entity("Domain.Models.Wallet", b =>
                {
                    b.HasOne("Domain.Models.User", null)
                        .WithOne("Wallet")
                        .HasForeignKey("Domain.Models.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Domain.Models.Book", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("Domain.Models.PurchaseHistory", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("PurchaseHistories");

                    b.Navigation("Wallet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
