// <auto-generated />
using System;
using Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(HarryPotterContext))]
    [Migration("20240129154423_DeleteAuthor")]
    partial class DeleteAuthor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Author", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("authorId");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("authorName");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("AuthorId")
                        .HasName("PK__author__8E2731B93441940C");

                    b.ToTable("author", (string)null);

                    b.HasData(
                        new
                        {
                            AuthorId = new Guid("28fcabdd-44ef-47f2-ac09-d96e955990c4"),
                            AuthorName = "J.K Rowling",
                            IsDeleted = false
                        },
                        new
                        {
                            AuthorId = new Guid("be406e3e-922a-4bc7-a2af-0f539ee4658a"),
                            AuthorName = "Alan Rickman",
                            IsDeleted = false
                        },
                        new
                        {
                            AuthorId = new Guid("419809c8-1e5b-4a9a-b795-e1a49c32add1"),
                            AuthorName = "Stephen King",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Domain.Models.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bookId");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("authorId");

                    b.Property<string>("Genre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("genre");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("Pages")
                        .HasColumnType("int")
                        .HasColumnName("pages");

                    b.Property<DateTime?>("PubYear")
                        .HasColumnType("datetime")
                        .HasColumnName("pubYear");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("rating");

                    b.Property<int?>("StockBalance")
                        .HasColumnType("int")
                        .HasColumnName("stockBalance");

                    b.Property<string>("Summary")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("BookId")
                        .HasName("PK__book__8BE5A10DE068B40D");

                    b.HasIndex("AuthorId");

                    b.ToTable("book", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = new Guid("2739dcb3-33b4-4736-a40c-4cb13a04177a"),
                            AuthorId = new Guid("28fcabdd-44ef-47f2-ac09-d96e955990c4"),
                            Genre = "Action",
                            IsDeleted = false,
                            Pages = 250,
                            PubYear = new DateTime(2024, 1, 29, 15, 44, 23, 576, DateTimeKind.Utc).AddTicks(4115),
                            Rating = 4.5m,
                            StockBalance = 10,
                            Summary = "Action packed book",
                            Title = "Book 1"
                        },
                        new
                        {
                            BookId = new Guid("cd7dc22b-5710-4713-b8ae-fc78358f5a6e"),
                            AuthorId = new Guid("be406e3e-922a-4bc7-a2af-0f539ee4658a"),
                            Genre = "Comedy",
                            IsDeleted = false,
                            Pages = 300,
                            PubYear = new DateTime(2024, 1, 29, 15, 44, 23, 576, DateTimeKind.Utc).AddTicks(4122),
                            Rating = 3.7m,
                            StockBalance = 20,
                            Summary = "Very funny book",
                            Title = "Book 2"
                        },
                        new
                        {
                            BookId = new Guid("64e615ca-e052-47b2-a26d-6d98d63a27f8"),
                            AuthorId = new Guid("419809c8-1e5b-4a9a-b795-e1a49c32add1"),
                            Genre = "Drama",
                            IsDeleted = false,
                            Pages = 180,
                            PubYear = new DateTime(2024, 1, 29, 15, 44, 23, 576, DateTimeKind.Utc).AddTicks(4124),
                            Rating = 4.8m,
                            StockBalance = 10,
                            Summary = "So much drama",
                            Title = "Book 3"
                        });
                });

            modelBuilder.Entity("Domain.Models.PurchaseHistory", b =>
                {
                    b.Property<Guid>("PurchaseHistoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("purchaseHistoryId");

                    b.Property<DateTime?>("TimeOfPurchase")
                        .HasColumnType("datetime")
                        .HasColumnName("timeOfPurchase");

                    b.Property<int?>("TotalPrice")
                        .HasColumnType("int")
                        .HasColumnName("totalPrice");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.HasKey("PurchaseHistoryId")
                        .HasName("PK__purchase__0261226C79359CBF");

                    b.HasIndex("UserId");

                    b.ToTable("purchaseHistory", (string)null);

                    b.HasData(
                        new
                        {
                            PurchaseHistoryId = new Guid("6bc02deb-f4c6-4b21-ab5f-38d6660d6c01"),
                            TimeOfPurchase = new DateTime(2024, 1, 29, 15, 44, 23, 576, DateTimeKind.Utc).AddTicks(4181),
                            TotalPrice = 50,
                            UserId = new Guid("95719511-516c-4ae7-b270-cb03d1f1d018")
                        },
                        new
                        {
                            PurchaseHistoryId = new Guid("31db8645-1463-4c2b-bf8c-7fe3afe16479"),
                            TimeOfPurchase = new DateTime(2024, 1, 29, 15, 44, 23, 576, DateTimeKind.Utc).AddTicks(4182),
                            TotalPrice = 30,
                            UserId = new Guid("95719511-516c-4ae7-b270-cb03d1f1d018")
                        },
                        new
                        {
                            PurchaseHistoryId = new Guid("a0438ac8-ee5e-4065-91cd-43eb5eabfb61"),
                            TimeOfPurchase = new DateTime(2024, 1, 29, 15, 44, 23, 576, DateTimeKind.Utc).AddTicks(4183),
                            TotalPrice = 25,
                            UserId = new Guid("95719511-516c-4ae7-b270-cb03d1f1d018")
                        });
                });

            modelBuilder.Entity("Domain.Models.Receipt", b =>
                {
                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReceiptId");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bookId");

                    b.Property<DateTime?>("DateDetail")
                        .HasColumnType("datetime")
                        .HasColumnName("dateDetail");

                    b.Property<int?>("PricePerUnit")
                        .HasColumnType("int")
                        .HasColumnName("pricePerUnit");

                    b.Property<Guid?>("PurchaseHistoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("purchaseHistoryId");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("ReceiptId")
                        .HasName("PK__purchase__FA43B55BADA17CED");

                    b.HasIndex("BookId");

                    b.HasIndex("PurchaseHistoryId");

                    b.ToTable("Receipt", (string)null);

                    b.HasData(
                        new
                        {
                            ReceiptId = new Guid("46676ea5-1eb9-48e2-96bc-12b04f010ba2"),
                            BookId = new Guid("2739dcb3-33b4-4736-a40c-4cb13a04177a"),
                            DateDetail = new DateTime(2024, 1, 29, 15, 44, 23, 576, DateTimeKind.Utc).AddTicks(4204),
                            PricePerUnit = 100,
                            PurchaseHistoryId = new Guid("6bc02deb-f4c6-4b21-ab5f-38d6660d6c01"),
                            Quantity = 2
                        },
                        new
                        {
                            ReceiptId = new Guid("1fe707be-2bd9-4989-afe9-1791b77c7e25"),
                            BookId = new Guid("cd7dc22b-5710-4713-b8ae-fc78358f5a6e"),
                            DateDetail = new DateTime(2024, 1, 29, 15, 44, 23, 576, DateTimeKind.Utc).AddTicks(4206),
                            PricePerUnit = 150,
                            PurchaseHistoryId = new Guid("31db8645-1463-4c2b-bf8c-7fe3afe16479"),
                            Quantity = 1
                        },
                        new
                        {
                            ReceiptId = new Guid("149cb5f2-fdf1-4536-a45c-091987317f32"),
                            BookId = new Guid("64e615ca-e052-47b2-a26d-6d98d63a27f8"),
                            DateDetail = new DateTime(2024, 1, 29, 15, 44, 23, 576, DateTimeKind.Utc).AddTicks(4207),
                            PricePerUnit = 80,
                            PurchaseHistoryId = new Guid("a0438ac8-ee5e-4065-91cd-43eb5eabfb61"),
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("firstName");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("role");

                    b.Property<string>("SurName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("surName");

                    b.Property<string>("TelephoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telephoneNumber");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("userName");

                    b.HasKey("UserId")
                        .HasName("PK__user__CB9A1CFF7FE751DC");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("95719511-516c-4ae7-b270-cb03d1f1d018"),
                            UserName = "AnvändareTestKöphistorik"
                        });
                });

            modelBuilder.Entity("Domain.Models.Wallet", b =>
                {
                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("walletId");

                    b.Property<int?>("Balance")
                        .HasColumnType("int")
                        .HasColumnName("balance");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId");

                    b.HasKey("WalletId")
                        .HasName("PK__wallet__3785C8706E62B1A8");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("wallet", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Book", b =>
                {
                    b.HasOne("Domain.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("FK__book__authorId__4222D4EF");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Domain.Models.PurchaseHistory", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("PurchaseHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__purchaseH__userI__412EB0B6");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Receipt", b =>
                {
                    b.HasOne("Domain.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId");

                    b.HasOne("Domain.Models.PurchaseHistory", "PurchaseHistories")
                        .WithMany("Receipts")
                        .HasForeignKey("PurchaseHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__purchaseD__purch__4316F928");

                    b.Navigation("Book");

                    b.Navigation("PurchaseHistories");
                });

            modelBuilder.Entity("Domain.Models.Wallet", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("Domain.Models.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Domain.Models.PurchaseHistory", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("PurchaseHistories");

                    b.Navigation("Wallet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
